sudo: required
services:
  - docker
language: generic

before_install:
  - docker build -t edoparearyee/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true edoparearyee/docker-react npm run test
